name: Build Workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'

      - name: Install dependencies
        run: npm install
      
 #      - name: Run Tests
 #       run: npm run test