name: Build branches

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'

      - name: Install dependencies
        run: npm install
      
 #      - name: Run Tests
 #       run: npm run test

      - name: Compute version
        run: |
          git config --global user.name "Lectra CI User"
          git config --global user.email "lectra.ci.user@lectra.com"
          npm version patch