name: Deploy Workflow

on:
  push:
    branches-ignore:
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/gallium'

      - name: Update project version
        run: |
          git config --global user.name "Lectra CI User"
          git config --global user.email "lectra.ci.user@lectra.com"
          npm version patch
      
      - name: Get project Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Show project version
        run: |
          echo ${{ steps.package-version.outputs.current-version }}
            
            
          

#      - name: Install dependencies
#        run: npm install
      
 #      - name: Run Tests
 #       run: npm run test     

#      - name: Commit and Push
#        run: | 
#          git push origin HEAD:main
#          git push origin HEAD:main --tags; 

     # - name: Create a GitHub release
      #  uses: ncipollo/release-action@v1
       # with:
      #    tag: ${{ steps.package-version.outputs.current-version }}
       #   name: ${{ steps.package-version.outputs.current-version }}
       #   body: ${{ steps.package-version.outputs.current-version }}
      
